import type { EditorTool } from './types';
import {
  MagicWandIcon, BackgroundIcon, EnhanceIcon, AnimeIcon, CartoonIcon, PaintingIcon,
  PhotoIcon, FilmIcon, CyberpunkIcon, VintageIcon, ThreeDIcon, PixelArtIcon, WatercolorIcon,
  SketchIcon, FantasyIcon, SteampunkIcon, PopArtIcon, SurrealIcon, MinimalistIcon,
  GothicIcon, AbstractIcon, GraffitiIcon,
} from './components/Icons';

export const TOOLS: EditorTool[] = [
  // Custom
  {
    id: 'custom-prompt',
    name: 'Custom',
    description: 'Write your own prompt.',
    icon: MagicWandIcon,
    prompt: '', // This will be user-defined
    category: 'Enhancement',
  },
  // Enhancement
  {
    id: 'upscale',
    name: 'Upscale 2x',
    description: 'Increase resolution and details.',
    icon: EnhanceIcon,
    prompt: 'Upscale this image to twice its original resolution. Enhance details, sharpen textures, and remove any compression artifacts to make it look high-definition. Do not change the content or style.',
    category: 'Enhancement',
  },
  // Style
  {
    id: 'photorealistic',
    name: 'Photorealistic',
    description: 'Make it look like a real photo.',
    icon: PhotoIcon,
    prompt: "Transform this image to look like a high-resolution, realistic photograph. Adjust lighting, textures, and focus to achieve a photorealistic effect, as if it were captured with a professional camera.",
    category: 'Style',
  },
  {
    id: 'anime',
    name: 'Anime',
    description: 'Convert to Japanese anime style.',
    icon: AnimeIcon,
    prompt: 'Convert this image into a vibrant, high-quality anime style. Use bold lines, expressive eyes, and classic cel-shading techniques.',
    category: 'Style',
  },
  {
    id: 'cartoon',
    name: 'Cartoon',
    description: 'Give it a fun, cartoonish look.',
    icon: CartoonIcon,
    prompt: 'Redraw this image in a playful cartoon style, with simplified shapes, thick outlines, and bright, flat colors.',
    category: 'Style',
  },
  {
    id: 'painting',
    name: 'Oil Painting',
    description: 'Look like an oil painting.',
    icon: PaintingIcon,
    prompt: 'Transform this image into a classical oil painting. Emphasize brush strokes, rich textures, and dramatic lighting.',
    category: 'Style',
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    description: 'Dramatic black and white.',
    icon: FilmIcon,
    prompt: 'Re-render this image in a dramatic film noir style. Use high-contrast black and white, deep shadows, and a cinematic, moody atmosphere.',
    category: 'Style',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon-drenched futuristic look.',
    icon: CyberpunkIcon,
    prompt: 'Convert this image to a cyberpunk aesthetic, featuring neon lights, futuristic elements, and a gritty, high-tech atmosphere.',
    category: 'Style',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Give it a retro, aged photo look.',
    icon: VintageIcon,
    prompt: 'Apply a vintage photo effect to this image. Give it a faded, sepia-toned look with film grain and slight imperfections, as if it were from the 1970s.',
    category: 'Style',
  },
  {
    id: '3d-render',
    name: '3D Render',
    description: 'Make it look like a 3D model.',
    icon: ThreeDIcon,
    prompt: 'Transform this image into a polished 3D render. It should look like a detailed digital model with realistic lighting and materials.',
    category: 'Style',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    description: 'Retro 8-bit video game style.',
    icon: PixelArtIcon,
    prompt: 'Convert this image into 8-bit pixel art. Use a limited color palette and blocky pixels to create a retro video game look.',
    category: 'Style',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft, blended watercolor style.',
    icon: WatercolorIcon,
    prompt: 'Redraw this image in a watercolor painting style, with soft edges, transparent layers, and a delicate, blended appearance.',
    category: 'Style',
  },
  {
    id: 'sketch',
    name: 'Pencil Sketch',
    description: 'Like a hand-drawn sketch.',
    icon: SketchIcon,
    prompt: 'Transform this image into a detailed pencil sketch. Use various shading techniques to create a realistic, hand-drawn look.',
    category: 'Style',
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'Magical, epic fantasy art.',
    icon: FantasyIcon,
    prompt: 'Re-imagine this image in an epic fantasy art style. Add magical elements, dramatic lighting, and intricate details worthy of a fantasy world.',
    category: 'Style',
  },
  {
    id: 'steampunk',
    name: 'Steampunk',
    description: 'Victorian-era futuristic style.',
    icon: SteampunkIcon,
    prompt: 'Convert this image to a steampunk style, incorporating gears, clockwork, brass, and Victorian-era fashion and technology.',
    category: 'Style',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    description: 'Bold, Warhol-inspired art.',
    icon: PopArtIcon,
    prompt: 'Transform this image into a Pop Art style inspired by Andy Warhol. Use bold colors, screen-printing effects, and repeated patterns.',
    category: 'Style',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    description: 'Dreamlike and bizarre art.',
    icon: SurrealIcon,
    prompt: 'Re-create this image in a surrealist style, inspired by Salvador Dalí. It should be dreamlike, bizarre, and defy logical explanation.',
    category: 'Style',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean lines and simple forms.',
    icon: MinimalistIcon,
    prompt: 'Redraw this image in a minimalist style. Use clean lines, simple geometric shapes, and a limited color palette to convey the essence of the subject.',
    category: 'Style',
  },
  {
    id: 'gothic',
    name: 'Gothic',
    description: 'Dark, moody, gothic art.',
    icon: GothicIcon,
    prompt: 'Transform this image into a gothic art style. Use dark tones, dramatic shadows, and ornate, macabre details.',
    category: 'Style',
  },
  {
    id: 'abstract',
    name: 'Abstract',
    description: 'Non-representational art.',
    icon: AbstractIcon,
    prompt: 'Convert this image into an abstract piece of art. Focus on shapes, colors, and forms rather than a realistic depiction.',
    category: 'Style',
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    description: 'Urban street art style.',
    icon: GraffitiIcon,
    prompt: 'Re-imagine this image as urban graffiti art. Use spray paint textures, bold lettering, and a vibrant, street-art aesthetic.',
    category: 'Style',
  },
  // Background
  {
    id: 'remove-bg',
    name: 'Remove BG',
    description: 'Remove the background.',
    icon: BackgroundIcon,
    prompt: 'Carefully and precisely remove the background from this image, leaving only the main subject. The output must be an image with a transparent background.',
    category: 'Background',
  },
  {
    id: 'change-bg-forest',
    name: 'Forest BG',
    description: 'Place in a lush forest.',
    icon: BackgroundIcon,
    prompt: 'Keep the main subject of the image but replace the background with a beautiful, lush, and dense forest scene. The lighting on the subject should match the new background.',
    category: 'Background',
  },
   {
    id: 'change-bg-city',
    name: 'City BG',
    description: 'Place in a bustling city.',
    icon: BackgroundIcon,
    prompt: 'Keep the main subject of the image but replace the background with a bustling, modern cityscape at night with neon lights. The lighting on the subject should match the new background.',
    category: 'Background',
  },
];
